name: sys_origin
exp_dir: ./exps/dipo/denoiser
data_root: /horizon-bucket/robot_lab/users/ruiqi.wu/robot/dataset/blender
n_time_samples: 16
loss_fg_weight: 0.01
img_drop_prob: 0.1
guidance_scaler: 0.5
graph_drop_prob: 0.5
model:
  name: denoiser
  in_ch: 6
  attn_dim: 128
  n_head: 4
  n_layers: 6
  dropout: 0.1
  K: 32
  mode_num: 5
  img_emb_dims:
  - 768
  - 128
  cat_drop_prob: 0.5
scheduler:
  name: ddpm
  config:
    num_train_timesteps: 1000
    beta_schedule: linear
    prediction_type: epsilon
lr_scheduler_adapter:
  name: LinearWarmupCosineAnnealingLR
  warmup_epochs: 3
  max_epochs: 200
  warmup_start_lr: 1.0e-06
  eta_min: 1.0e-05
optimizer_adapter:
  name: AdamW
  args:
    lr: 0.0005
    betas:
    - 0.9
    - 0.99
    eps: 1.0e-15
lr_scheduler_cage:
  name: LinearWarmupCosineAnnealingLR
  warmup_epochs: 3
  max_epochs: 200
  warmup_start_lr: 1.0e-06
  eta_min: 1.0e-05
optimizer_cage:
  name: AdamW
  args:
    lr: 5.0e-05
    betas:
    - 0.9
    - 0.99
    eps: 1.0e-15
hparams:
  name: sys_origin
  exp_dir: ./exps/dipo/denoiser
  data_root: /horizon-bucket/robot_lab/users/ruiqi.wu/robot/dataset/blender
  n_time_samples: 16
  loss_fg_weight: 0.01
  img_drop_prob: 0.1
  guidance_scaler: 0.5
  graph_drop_prob: 0.5
  model:
    name: denoiser
    in_ch: 6
    attn_dim: 128
    n_head: 4
    n_layers: 6
    dropout: 0.1
    K: 32
    mode_num: 5
    img_emb_dims:
    - 768
    - 128
    cat_drop_prob: 0.5
  scheduler:
    name: ddpm
    config:
      num_train_timesteps: 1000
      beta_schedule: linear
      prediction_type: epsilon
  lr_scheduler_adapter:
    name: LinearWarmupCosineAnnealingLR
    warmup_epochs: 3
    max_epochs: 200
    warmup_start_lr: 1.0e-06
    eta_min: 1.0e-05
  optimizer_adapter:
    name: AdamW
    args:
      lr: 0.0005
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
  lr_scheduler_cage:
    name: LinearWarmupCosineAnnealingLR
    warmup_epochs: 3
    max_epochs: 200
    warmup_start_lr: 1.0e-06
    eta_min: 1.0e-05
  optimizer_cage:
    name: AdamW
    args:
      lr: 5.0e-05
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
